const measures=[
{type:"Федеральная",title:"Единое пособие",min:0,max:16,text:"Для беременных женщин и семей с детьми. Право зависит не только от возраста ребёнка, но и от доходов, имущества, занятости и других условий.",extra:"Нужно проверить дополнительные условия"},
{type:"Федеральная",title:"Материнский капитал",min:0,max:18,text:"Государственная поддержка семей с детьми. Возможность получения и распоряжения зависит от даты рождения детей и других обстоятельств.",extra:"Проверьте условия вашей семьи"},
{type:"Федеральная",title:"Пособие по уходу за ребёнком до 1,5 лет",min:0,max:1.49,text:"Мера поддержки в период ухода за маленьким ребёнком. Условия различаются в зависимости от статуса получателя.",extra:"Подходит по возрасту ребёнка"},
{type:"Региональная",region:"Красноярский край",title:"Меры поддержки семей Красноярского края",min:0,max:17,text:"Региональные выплаты и льготы зависят от категории семьи и конкретной меры. База будет наполняться только по официальным источникам.",extra:"Раздел готовится"},
{type:"Региональная",region:"Самарская область",title:"Меры поддержки семей Самарской области",min:0,max:17,text:"Региональные выплаты и льготы зависят от категории семьи и конкретной меры. База будет наполняться только по официальным источникам.",extra:"Раздел готовится"}];
const children=document.querySelector("#children"),ages=document.querySelector("#ages");
function drawAges(){let n=Math.max(0,Math.min(15,+children.value||0));ages.innerHTML=n?'<h3>Возраст детей</h3><div class="age-grid">'+Array.from({length:n},(_,i)=>'<label>Ребёнок '+(i+1)+'<input class="age" type="number" min="0" max="30" step="0.1" placeholder="лет" required></label>').join("")+'</div>':""}children.addEventListener("input",drawAges);drawAges();
const extra=document.querySelector("#extraQuestions");
function drawExtra(){
 const n=+children.value||0;
 extra.innerHTML='<details><summary>Уточнить ситуацию семьи</summary><div class="grid2"><label>Возраст мамы<input id="motherAge" type="number" min="14" max="80" placeholder="Необязательно"></label><label>Дети родились одновременно?<select id="multipleBirth"><option value="">Не относится</option><option value="yes">Да</option><option value="no">Нет</option></select></label></div><label><input id="student1822" type="checkbox"> Есть ребёнок 18–22 лет, который учится очно</label></details>';
}
children.addEventListener("input",drawExtra);drawExtra();
document.querySelector("#familyForm").addEventListener("submit",e=>{e.preventDefault();let region=document.querySelector("#region").value,member=+document.querySelector("#members").value,kids=+children.value,aa=[...document.querySelectorAll(".age")].map(x=>+x.value),preg=document.querySelector("#pregnant").checked,dis=document.querySelector("#disabledChild").checked;
let relevant=measures.filter(m=>(!m.region||m.region===region)&&(aa.some(a=>a>=m.min&&a<=m.max)||(preg&&m.title==="Единое пособие")));
document.querySelector("#summary").textContent=region+" • членов семьи: "+member+" • детей: "+kids+(preg?" • беременность":"")+(dis?" • есть ребёнок с инвалидностью":"")+". Ниже меры, которые стоит проверить по указанным данным.";
let fed=relevant.filter(x=>x.type==="Федеральная"),reg=relevant.filter(x=>x.type==="Региональная");const render=(title,a)=>a.length?'<h3 class="group-title">'+title+'</h3>'+a.map(m=>'<article class="measure"><div class="measure-top"><div><h3>'+m.title+'</h3><span class="tag">'+m.type+'</span></div></div><p>'+m.text+'</p><p class="status">● '+m.extra+'</p></article>').join(""):"";
document.querySelector("#cards").innerHTML=render("Федеральные меры",fed)+render("Региональные меры",reg);document.querySelector("#results").classList.remove("hidden");document.querySelector("#results").scrollIntoView({behavior:"smooth"})});
document.querySelector("#edit").onclick=()=>document.querySelector(".form-card").scrollIntoView({behavior:"smooth"});